### ISSUE TITLE
fullScreenMode not working

### ISSUE THREAD

**Issue by jonDel** [mrbot-ai/rasa-webchat#7] opened 2018-10-17 12:10 UTC
A similar issue was reported on the original repository, see:  Wolox/react-chat-widget/issues/76
Any chance of a fix?

Thanks in advance,

**Comment by TheoTomalty** [comment] 2018-10-18 18:08
Hi @jonDel, this should be fixed on the exporter branch, let me know if you are still having problems using it.

**Comment by jonDel** [comment] 2018-10-19 14:43
Thanks @TheoTomalty . I'm using https://storage.googleapis.com/mrbot-cdn/webchat-latest.js as source for the script. Is there a stored version for the exported branch version besides the master branch one?

**Comment by TheoTomalty** [comment] 2018-10-19 16:18
@jonDel I will deploy the new version so that you won't have to change webchat-latest.js. Will let you know when it's done.

**Comment by TheoTomalty** [comment] 2018-10-24 14:29
Hi @jonDel, the latest version is up and running so feel free to try again using webchat-latest.js. Another option is to load webchat-0.4.0.js instead, which is currently identical but won't be changed in the future.

Let me know if this fixes your problem.

**Comment by jonDel** [comment] 2018-10-25 17:44
Hi @TheoTomalty , it seems ok, besides the fact the "initPayload" option seems not to work in fullscreen mode. Also, the chat immediately shows up in fullscreen, instead of showing up only when clicking in the widget (I dont know if it is the expected result)

**Comment by TheoTomalty** [comment] 2018-10-29 21:18
Thanks @jonDel for letting us know about the initPayload bug in fullscreen mode, it should be fixed in 0.4.1 (webchat-latest will have the most recent version). Now the initPayload is sent when the component mounts.

To answer your question about the fullscreen mode opening up automatically, yes this is the intended behaviour. The widget is to embed into a webpage whereas fullscreen mode should be launched in its own window.

**Comment by TheoTomalty** [comment] 2018-10-29 21:19
I'm closing this issue now but feel free to open up another one if you have any more issues/requests

**Closed by TheoTomalty** 2018-10-29 21:20 UTC
Labels: bug

**Comment by dliuproduction** [comment] 2018-11-22 15:31
This is fixed and will be up in the next release. @jonDel
